#!/usr/bin/env python3
"""
Burn an official EU AI-disclosure icon into an image (part of the pixels, not an overlay).

Only needs Pillow. The icons are pre-rendered, trimmed PNGs from the official EU SVG pack
(assets/icons/), so no SVG renderer is required at runtime.

Examples
  python apply_disclosure.py cover.jpg                     # basic "AI" icon, auto corner/style/tone
  python apply_disclosure.py photo.jpg --source modified   # AI-edited photo: same icon, XMP says modified
  python apply_disclosure.py cover.jpg --label generated   # "AI GENERATED" pill, only on request
  python apply_disclosure.py cover.jpg --analyze           # JSON only, writes nothing

Labels (EU icon set):
  ai         basic icon "AI" (default)  -> the element the Code of Practice requires (Measure 1.1(a))
  generated  "AI GENERATED"             -> optional text variant: fully generated by AI
  modified   "AI MODIFIED"              -> optional text variant: existing content partly changed by AI

Source (what the XMP metadata says, independent of the visible icon):
  generated  fully generated by AI (default, or taken from --label generated)
  modified   existing human-made content partly changed by AI (or taken from --label modified)
"""
import argparse
import json
import sys
from pathlib import Path

from PIL import Image, ImageOps, ImageStat, PngImagePlugin

ICON_DIR = Path(__file__).resolve().parent.parent / "assets" / "icons"
CORNERS = ["br", "bl", "tr", "tl"]  # preference order
CALM = 20  # busyness (std-dev of luminance) up to which an area counts as calm
MIN_ICON_PX = 24
# IPTC Digital Source Type vocabulary (machine-readable, travels in XMP)
SOURCE_TYPE = {
    "generated": "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia",
    "modified": "http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia",
}


def icon_box(img_w, img_h, label, scale, margin):
    """Return icon pixel size and margin, derived from the shorter image side."""
    short = min(img_w, img_h)
    ref = Image.open(ICON_DIR / f"{label}_black_solid.png")
    # same height for the round badge and the pills: scale * short side
    h = max(MIN_ICON_PX, round(short * scale))
    w = round(ref.width * h / ref.height)
    m = max(8, round(short * margin))
    return w, h, m


def corner_xy(corner, img_w, img_h, w, h, m):
    x = m if corner[1] == "l" else img_w - w - m
    y = m if corner[0] == "t" else img_h - h - m
    return x, y


def patch_stats(img, box):
    """Mean luminance and busyness (std-dev) of the area under the icon."""
    gray = img.convert("L").crop(box)
    st = ImageStat.Stat(gray)
    return st.mean[0], st.stddev[0]


def pick_style(busyness):
    """Official 50 % variant on calm areas, solid where detail would show through it."""
    return "transparent" if busyness <= CALM else "solid"


def pick_tone(luminance, style):
    """Solid: the disc contrasts with the background. Transparent: the letters do
    (black_transparent has white letters, white_transparent dark ones)."""
    light = luminance > 140
    if style == "solid":
        return "black" if light else "white"
    return "white" if light else "black"


def analyze(img, label, scale, margin):
    w, h, m = icon_box(img.width, img.height, label, scale, margin)
    out = {}
    for c in CORNERS:
        x, y = corner_xy(c, img.width, img.height, w, h, m)
        # sample a slightly larger area than the icon itself
        pad = round(h * 0.5)
        box = (max(0, x - pad), max(0, y - pad), min(img.width, x + w + pad), min(img.height, y + h + pad))
        lum, busy = patch_stats(img, box)
        out[c] = {"luminance": round(lum, 1), "busyness": round(busy, 1)}
    # prefer bottom-right unless it is clearly busier than the calmest corner
    calmest = min(CORNERS, key=lambda c: out[c]["busyness"])
    # busyness is the std-dev of luminance (0 = flat color); keep a consistent corner unless it would sit on detail
    suggested = "br" if out["br"]["busyness"] <= max(CALM, out[calmest]["busyness"] * 2 + 10) else calmest
    style = pick_style(out[suggested]["busyness"])
    return {
        "size": [img.width, img.height],
        "icon_px": [w, h],
        "margin_px": m,
        "corners": out,
        "suggested_corner": suggested,
        "suggested_style": style,
        "suggested_tone": pick_tone(out[suggested]["luminance"], style),
        "small_format": min(img.width, img.height) < 500,
    }


def xmp_packet(source):
    return (
        '<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>'
        '<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
        '<rdf:Description rdf:about="" xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" '
        'xmlns:dc="http://purl.org/dc/elements/1.1/">'
        f"<Iptc4xmpExt:DigitalSourceType>{SOURCE_TYPE[source]}</Iptc4xmpExt:DigitalSourceType>"
        '<dc:description><rdf:Alt><rdf:li xml:lang="x-default">'
        f'{"Generated with AI" if source == "generated" else "Modified with AI"}'
        "</rdf:li></rdf:Alt></dc:description>"
        "</rdf:Description></rdf:RDF></x:xmpmeta>"
        '<?xpacket end="w"?>'
    ).encode("utf-8")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("input")
    p.add_argument("--label", choices=["ai", "generated", "modified"], default="ai")
    p.add_argument("--source", choices=["generated", "modified"],
                   help="what the XMP says; default: from --label, else generated")
    p.add_argument("-o", "--output", help="default: <name>-ai.<ext> next to the input")
    p.add_argument("--corner", choices=["auto"] + CORNERS, default="auto")
    p.add_argument("--tone", choices=["auto", "black", "white"], default="auto",
                   help="icon color; auto = the variant that stays readable on the area under the icon")
    p.add_argument("--style", choices=["auto", "solid", "transparent"], default="auto",
                   help="auto = official 50%% transparent variant on calm areas, solid on busy ones")
    p.add_argument("--scale", type=float, default=0.04,
                   help=f"icon height as fraction of shorter side (min {MIN_ICON_PX} px)")
    p.add_argument("--margin", type=float, default=0.03, help="distance from edges as fraction of shorter side")
    p.add_argument("--analyze", action="store_true", help="print analysis JSON and exit")
    p.add_argument("--overwrite", action="store_true", help="allow writing over an existing output file")
    a = p.parse_args()

    if a.label != "ai" and a.source and a.source != a.label:
        p.error(f"--source {a.source} contradicts --label {a.label}")
    source = a.source or (a.label if a.label != "ai" else "generated")

    src = Path(a.input)
    # apply EXIF orientation first, so the icon lands in the corner the viewer actually sees
    img = ImageOps.exif_transpose(Image.open(src))
    info = analyze(img, a.label, a.scale, a.margin)
    if a.analyze:
        print(json.dumps(info, indent=2))
        return

    corner = info["suggested_corner"] if a.corner == "auto" else a.corner
    under = info["corners"][corner]
    style = pick_style(under["busyness"]) if a.style == "auto" else a.style
    tone = pick_tone(under["luminance"], style) if a.tone == "auto" else a.tone

    w, h = info["icon_px"]
    m = info["margin_px"]
    icon = Image.open(ICON_DIR / f"{a.label}_{tone}_{style}.png").convert("RGBA")
    icon = icon.resize((w, h), Image.LANCZOS)
    x, y = corner_xy(corner, img.width, img.height, w, h, m)

    base = img.convert("RGBA")
    base.alpha_composite(icon, (x, y))

    out = Path(a.output) if a.output else src.with_name(f"{src.stem}-ai{src.suffix}")
    if out.resolve() == src.resolve() and not a.overwrite:
        sys.exit("Refusing to overwrite the input. Pass --overwrite (keep a copy of the original first).")
    if out.exists() and out.resolve() != src.resolve() and not a.overwrite:
        sys.exit(f"{out} exists. Pass --overwrite or choose another -o.")

    fmt = (out.suffix.lower().lstrip(".") or "png").replace("jpg", "jpeg")
    kw = {}
    if img.info.get("icc_profile"):
        kw["icc_profile"] = img.info["icc_profile"]
    exif = img.getexif()
    if exif:
        kw["exif"] = exif
    if fmt == "png":
        # Pillow's PNG writer ignores xmp=, so XMP goes into the standard iTXt chunk
        meta = PngImagePlugin.PngInfo()
        meta.add_itxt("XML:com.adobe.xmp", xmp_packet(source).decode("utf-8"))
        kw["pnginfo"] = meta
    elif fmt in ("jpeg", "webp", "tiff"):
        kw["xmp"] = xmp_packet(source)
    if fmt == "jpeg":
        final = base.convert("RGB")
        kw.update(quality=95, subsampling=0, optimize=True)
    elif fmt == "webp":
        final = base if img.mode in ("RGBA", "LA") else base.convert("RGB")
        kw.update(quality=95)
    else:
        final = base if img.mode in ("RGBA", "LA", "P") else base.convert("RGB")
    try:
        final.save(out, fmt.upper(), **kw)
    except TypeError:  # very old Pillow without xmp support
        kw.pop("xmp", None)
        final.save(out, fmt.upper(), **kw)

    print(json.dumps({
        "output": str(out),
        "label": a.label,
        "source": source,
        "corner": corner,
        "tone": tone,
        "style": style,
        "icon_px": [w, h],
        "position_px": [x, y],
        "digital_source_type": SOURCE_TYPE[source],
    }, indent=2))


if __name__ == "__main__":
    main()
