#!/usr/bin/env python3
"""
Burn an official EU AI-disclosure icon into an image (part of the pixels, not an overlay).

Only needs Pillow. The icons are pre-rendered, trimmed PNGs from the official EU SVG pack
(assets/icons/), so no SVG renderer is required at runtime.

Examples
  python apply_disclosure.py cover.jpg --label generated
  python apply_disclosure.py photo.jpg --label modified --corner bl -o photo-ai.jpg
  python apply_disclosure.py cover.jpg --analyze          # JSON only, writes nothing

Labels (EU icon set):
  ai         basic icon "AI"            -> AI was involved, or small formats (thumbnails, avatars)
  generated  "AI GENERATED"             -> fully generated by AI (only the prompt is human)
  modified   "AI MODIFIED"              -> existing human-made content partly changed by AI
"""
import argparse
import json
import sys
from pathlib import Path

from PIL import Image, ImageStat

ICON_DIR = Path(__file__).resolve().parent.parent / "assets" / "icons"
CORNERS = ["br", "bl", "tr", "tl"]  # preference order
# IPTC Digital Source Type vocabulary (machine-readable, travels in XMP)
SOURCE_TYPE = {
    "ai": "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia",
    "generated": "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia",
    "modified": "http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia",
}


def icon_box(img_w, img_h, label, scale, margin):
    """Return icon pixel size and margin, derived from the shorter image side."""
    short = min(img_w, img_h)
    ref = Image.open(ICON_DIR / f"{label}_black_solid.png")
    # pill labels: height = scale * short side; round "AI" badge is a bit larger to stay legible
    h = max(28, round(short * (scale if label != "ai" else scale * 1.75)))
    w = round(ref.width * h / ref.height)
    m = max(8, round(short * margin))
    return w, h, m


def corner_xy(corner, img_w, img_h, w, h, m):
    x = m if corner[1] == "l" else img_w - w - m
    y = m if corner[0] == "t" else img_h - h - m
    return x, y


def patch_stats(img, box):
    """Mean luminance and busyness (std-dev) of the area under the icon."""
    gray = img.convert("L").crop(box)
    st = ImageStat.Stat(gray)
    return st.mean[0], st.stddev[0]


def analyze(img, label, scale, margin):
    w, h, m = icon_box(img.width, img.height, label, scale, margin)
    out = {}
    for c in CORNERS:
        x, y = corner_xy(c, img.width, img.height, w, h, m)
        # sample a slightly larger area than the icon itself
        pad = round(h * 0.5)
        box = (max(0, x - pad), max(0, y - pad), min(img.width, x + w + pad), min(img.height, y + h + pad))
        lum, busy = patch_stats(img, box)
        out[c] = {"luminance": round(lum, 1), "busyness": round(busy, 1)}
    # prefer bottom-right unless it is clearly busier than the calmest corner
    calmest = min(CORNERS, key=lambda c: out[c]["busyness"])
    # busyness is the std-dev of luminance (0 = flat color); keep a consistent corner unless it would sit on detail
    suggested = "br" if out["br"]["busyness"] <= max(20, out[calmest]["busyness"] * 2 + 10) else calmest
    tone = "black" if out[suggested]["luminance"] > 140 else "white"
    return {
        "size": [img.width, img.height],
        "icon_px": [w, h],
        "margin_px": m,
        "corners": out,
        "suggested_corner": suggested,
        "suggested_tone": tone,
        "small_format": min(img.width, img.height) < 500,
    }


def xmp_packet(label):
    return (
        '<?xpacket begin="\ufeff" id="W5M0MpCehiHzreSzNTczkc9d"?>'
        '<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
        '<rdf:Description rdf:about="" xmlns:Iptc4xmpExt="http://iptc.org/std/Iptc4xmpExt/2008-02-29/" '
        'xmlns:dc="http://purl.org/dc/elements/1.1/">'
        f"<Iptc4xmpExt:DigitalSourceType>{SOURCE_TYPE[label]}</Iptc4xmpExt:DigitalSourceType>"
        '<dc:description><rdf:Alt><rdf:li xml:lang="x-default">'
        f'{"Generated with AI" if label != "modified" else "Modified with AI"}'
        "</rdf:li></rdf:Alt></dc:description>"
        "</rdf:Description></rdf:RDF></x:xmpmeta>"
        '<?xpacket end="w"?>'
    ).encode("utf-8")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("input")
    p.add_argument("--label", choices=["ai", "generated", "modified"], default="generated")
    p.add_argument("-o", "--output", help="default: <name>-ai.<ext> next to the input")
    p.add_argument("--corner", choices=["auto"] + CORNERS, default="auto")
    p.add_argument("--tone", choices=["auto", "black", "white"], default="auto",
                   help="pill color; auto = white pill on dark areas, black pill on light areas")
    p.add_argument("--style", choices=["solid", "transparent"], default="solid",
                   help="solid is more legible; transparent = official 50%% variant")
    p.add_argument("--scale", type=float, default=0.04, help="pill height as fraction of shorter side")
    p.add_argument("--margin", type=float, default=0.03, help="distance from edges as fraction of shorter side")
    p.add_argument("--analyze", action="store_true", help="print analysis JSON and exit")
    p.add_argument("--overwrite", action="store_true", help="allow writing over an existing output file")
    a = p.parse_args()

    src = Path(a.input)
    img = Image.open(src)
    info = analyze(img, a.label, a.scale, a.margin)
    if a.analyze:
        print(json.dumps(info, indent=2))
        return

    corner = info["suggested_corner"] if a.corner == "auto" else a.corner
    if a.tone == "auto":
        tone = "black" if info["corners"][corner]["luminance"] > 140 else "white"
    else:
        tone = a.tone

    w, h = info["icon_px"]
    m = info["margin_px"]
    icon = Image.open(ICON_DIR / f"{a.label}_{tone}_{a.style}.png").convert("RGBA")
    icon = icon.resize((w, h), Image.LANCZOS)
    x, y = corner_xy(corner, img.width, img.height, w, h, m)

    base = img.convert("RGBA")
    base.alpha_composite(icon, (x, y))

    out = Path(a.output) if a.output else src.with_name(f"{src.stem}-ai{src.suffix}")
    if out.resolve() == src.resolve() and not a.overwrite:
        sys.exit("Refusing to overwrite the input. Pass --overwrite (keep a copy of the original first).")
    if out.exists() and out.resolve() != src.resolve() and not a.overwrite:
        sys.exit(f"{out} exists. Pass --overwrite or choose another -o.")

    fmt = (out.suffix.lower().lstrip(".") or "png").replace("jpg", "jpeg")
    kw = {}
    if img.info.get("icc_profile"):
        kw["icc_profile"] = img.info["icc_profile"]
    exif = img.getexif()
    if exif:
        kw["exif"] = exif
    if fmt in ("jpeg", "webp", "png", "tiff"):
        kw["xmp"] = xmp_packet(a.label)
    if fmt == "jpeg":
        final = base.convert("RGB")
        kw.update(quality=95, subsampling=0, optimize=True)
    elif fmt == "webp":
        final = base if img.mode in ("RGBA", "LA") else base.convert("RGB")
        kw.update(quality=95)
    else:
        final = base if img.mode in ("RGBA", "LA", "P") else base.convert("RGB")
    try:
        final.save(out, fmt.upper(), **kw)
    except TypeError:  # very old Pillow without xmp support
        kw.pop("xmp", None)
        final.save(out, fmt.upper(), **kw)

    print(json.dumps({
        "output": str(out),
        "label": a.label,
        "corner": corner,
        "tone": tone,
        "style": a.style,
        "icon_px": [w, h],
        "position_px": [x, y],
        "digital_source_type": SOURCE_TYPE[a.label],
    }, indent=2))


if __name__ == "__main__":
    main()
